### ISSUE TITLE
404 error when processing Ao1ur52d5Os

### ISSUE THREAD

**Issue by kiang** [audreyt/pad2an#4]
http://pad.archive.tw:8080/https://hackpad.com/Ao1ur52d5Os

returned the following error message:
Error: SuperagentPromiseError: cannot GET https://hackpad.com/ep/pad/static/.com (404)

**Comment by audreyt** [comment]
Try http://pad.archive.tw:8080/https://hackpad.com/ep/pad/static/Ao1ur52d5Os

**Comment by kiang** [comment]
thanks, it works.
