### ISSUE TITLE
Make help page multi-lingual

### ISSUE THREAD

**Issue by patcon** [audreyt/pad2an#5]
Seems that http://archive.tw/ is now running a fork with minor differences in documentation.

Can we have a discussion about what changes could be made to allow the same codebase to run for both mandarin- and english-speaking audiences? :)

Thanks! (Would appreciate any context on forces at play that resulted in archive.tw going mandarin, so that I can understand what needs are)

**Comment by audreyt** [comment]
Hi! Thanks for noticing. I changed the URL in this repository to point to https://pad.archive.tw/ — archive.tw is https://github.com/audreyt/archive.tw

**Comment by patcon** [comment]
Sorry! This was unobservant on my part..!
